image: node:10.16.0

variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build
  - test

cache:
  key: "$CI_COMMIT_SHA"
  policy: pull
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
  except:
    - /^release_/
  cache:
    key: "$CI_COMMIT_SHA"
    policy: push
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - build
  script:
    - npm test

lint:
  stage: test
  dependencies:
    - build
  script:
    - npm run lint
